# Generated by Django 4.0.3 on 2022-08-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='modiified_at',
            new_name='modified_at',
        ),
    ]
