# Generated by Django 4.0.3 on 2022-08-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hook_text',
        ),
    ]
