# Generated by Django 4.0.3 on 2022-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_post_hook_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dong',
            name='gong_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
