# Generated by Django 4.0.3 on 2022-08-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_dong_gong_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dong',
            name='gong_content',
        ),
    ]
