# Generated by Django 4.0.3 on 2022-08-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_dong_gong_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='dong',
            options={'verbose_name_plural': '동아리'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '게시물'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='head_image',
            new_name='대표사진',
        ),
    ]
