# Generated by Django 4.0.3 on 2022-08-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='게시물종류',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='게시물',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='내용',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='작성일',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='작성자',
        ),
        migrations.RenameField(
            model_name='dong',
            old_name='content',
            new_name='동아리내용',
        ),
        migrations.RenameField(
            model_name='dong',
            old_name='head_image',
            new_name='동아리로고',
        ),
        migrations.RenameField(
            model_name='dong',
            old_name='title',
            new_name='동아리명',
        ),
        migrations.RenameField(
            model_name='dong',
            old_name='hook_text',
            new_name='요약문',
        ),
        migrations.RenameField(
            model_name='dong',
            old_name='author',
            new_name='작성자',
        ),
        migrations.RenameField(
            model_name='dong',
            old_name='file_upload',
            new_name='활동사진',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='내용',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='작성일',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='작성자',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='제목',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='카테고리',
        ),
    ]
