# Generated by Django 4.0.3 on 2022-08-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_name_category_게시물종류_rename_post_comment_게시물_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='카테고리',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
