# Generated by Django 4.0.3 on 2022-08-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_카테고리'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': '식당종류',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('식당이름', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logo/%Y/%m/%d/')),
                ('메뉴', models.ImageField(blank=True, null=True, upload_to='media/menu/%Y/%m/%d/')),
                ('전화번호', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_featured', to='blog.category')),
            ],
            options={
                'verbose_name_plural': '식당',
            },
        ),
    ]
