# Generated by Django 4.0.4 on 2022-09-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_category_res_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='작성자',
        ),
    ]
