# Generated by Django 4.0.4 on 2022-09-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_comment_게시물'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='게시물',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
