# Generated by Django 4.0.3 on 2022-08-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0002_major_remove_post_created_at_remove_post_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='School',
        ),
    ]
