# Generated by Django 4.0.3 on 2022-08-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0004_category_major_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]
