# Generated by Django 4.0.3 on 2022-08-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0007_faculty_remove_major_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
