# Generated by Django 4.0.3 on 2022-08-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0008_faculty_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='name',
            new_name='faculty_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='slug',
        ),
    ]
