# Generated by Django 4.0.3 on 2022-08-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_pages', '0009_rename_name_faculty_faculty_name_remove_faculty_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': '학부'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': '학교연락처'},
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_name',
            new_name='학부',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='content',
            new_name='전화번호',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='title',
            new_name='학과',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='faculty',
            new_name='학부',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='title',
            new_name='부서',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='content',
            new_name='전화번호',
        ),
    ]
