# Generated by Django 4.0.3 on 2022-08-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '식당종류'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': '식당'},
        ),
    ]
