# Generated by Django 4.0.3 on 2022-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_category_options_alter_restaurant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='open_close',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
