# Generated by Django 4.0.3 on 2022-08-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_open_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='close_day',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
