# Generated by Django 4.0.3 on 2022-08-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_close_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='open_close',
            field=models.TextField(max_length=200),
        ),
    ]
