# Generated by Django 4.0.3 on 2022-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurant_open_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.FileField(blank=True, null=True, upload_to='media/menu/%Y/%m/%d/'),
        ),
    ]
