# Generated by Django 4.0.3 on 2022-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurant_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='menu',
            new_name='menu1',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu2',
            field=models.FileField(blank=True, null=True, upload_to='media/menu/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu3',
            field=models.FileField(blank=True, null=True, upload_to='media/menu/%Y/%m/%d/'),
        ),
    ]
